---
version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html:ro
    environment:
      FOO: BAR
    ports:
      - '8080:80'

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80' # Disable HTTPS for local dev
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8080
        anonymous
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev # Enable dev mode
    ports:
      - '8000:80'
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
